# Conclusion

Over time, across these three controversial issues, we see the general public liberalizing on these topics. Although starting positions on the issues are quite conservative compared to today, throughout demographics and regions, on a trend over time, opinions have broadly shifted in favor of more abortion rights, increased tolerance for affirmative action, and against capital punishment. There are a couple notable exceptions: those identifying as conservative and extremely conservative have shifted *against* abortion rights in the last fifty years, and Black americans have retained fairly consistent opposition to capital punishment over time. These trends indicate an underlying dynamic to the way that public opinions change over time. Although changes often occur across identities, social groups and subcultures often move as a whole, in ways that both align with and diverge from the broader changes in social grouping.

The timing of the broader societal shifts is particularly interesting. Support for abortion, while steady in the general population prior to 1995, actually decreased between then and 2005, bounced back until 2010, and began increasing sharply after 2016. It is not a surprise that the major shfits in public opinion align with national elections where abortion rights were a major issue, and the last large uptick in support occurred under an administration opposed to abortion rights. Interestingly, the ongoing conservative opposition to abortion seems to be a fairly steady trend unrelated to contemporary political developments.

Meanwhile, trends in beliefs about affirmative action seem to be essentially continuous trends across time, aside from a notable jump in support specifically among students in 2010. It's not entirely clear what this jump in support is the result of - there was one notable Supreme Court Case (2009), but it does not have to do with students, and while a notable case, did not reach the kind of media saturation that enormous cases like Obergefell v. Hodges did.

Finally, opinions on the death penalty do seem to be influenced by news events. After a peak of support in 1985, we can see that DNA exoneration and the abolition of the death penalty in several states are associated with a change in the rate growing disfavor for the death penalty. Therefore, we can also understand these issues as being self-reinforcing: not only do the political opinions of individuals inform how governing rules are set up; but the rules and governments that are in place influence the opinions people hold.